

# Site settings
title: TheGambitier's Blog
subtitle:
email: blog.gambitier@gmail.com
description: Tech related tutorials.
baseurl: "/gambitier.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Akash Jadhav
street_address: 
city: Pandharpur
state: Maharashtra
zip_code: 413304
country: India
phone: (+91) 

# Build settings
gems: [jekyll-paginate] 
  
# Jekyll paginate settings
paginate: 4 
paginate_path: "/archive/page:num/"
paginate_path: /page:num/

# Social settings
500px_url:
facebook_url: https://www.facebook.com/
github_url: https://github.com/gambitier
gitlab_url:  
googleplus_url:  
instagram_url: 
linkedin_url:  https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown



#prose

prose:
  rooturl: 'BlogPosts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""

